### PR TITLE
feat: add ability to select and deselect all country or variant filters

### LINKED ISSUE #96: Button to show and hide all countries at once
It would be nice to be able to diasable and enble all countries at once. That way you can select just one or two countries to compare them side by side.

### PR DESCRIPTION
**Pull request by ivan-aksamentov**
Resolves #96

Adds "Select all" and "Deselect all" links to the filtering sidebar panels, which allow toggling all countries or variants

### CODE REVIEW

**Comment by ivan-aksamentov** [comment]
@jcscaptures This adds the "Select all" and "Deselect all" buttons/links you requested in #96.

If you have a spare second, could you please try this development version of the site:
https://covariants-git-feat-select-all.hodcroftlab.vercel.app/
and tell us what you think? Do you have any further suggestions?

**Comment by jcscaptures** [comment]
Awesome, looks good to me! I don't have any other suggestions right now.

**Comment by emmahodcroft** [comment]
This is soooo useful Ivan. I appreciate you doing this! I've tested it and it seems fab. If it's ready to merge, let's do it!

**Comment by emmahodcroft** [comment]
And @jcscaptures thank you for this great idea!

**Comment by emmahodcroft** [comment]
@jcscaptures Do you have a twitter handle so I can tag you for the idea on twitter? I'd need it in the next 20 mins or so. Thanks! (But I do a follow-up tweet after that if needed!)

**Comment by jcscaptures** [comment]
Ah sorry, I'm to late... It's @Jak0bsc

**Pull request merged**
