### PR TITLE
Chinese Simplified translation for all pages

### PR DESCRIPTION
**Pull request by tonyqus**
This PR is in progress

### CODE REVIEW

**Comment by tonyqus** [comment]
My translation task is done

**Comment by emmahodcroft** [comment]
@tonyqus Thank you so much for all of this work - it was an immense task and I really appreciate it! I'm starting the process of getting this live now. I will write a twitter thread to announce it - do you have a twitter handle that I can acknowledge for all your work? If not I can just write your name! :)

**Comment by ivan-aksamentov** [comment]
@tonyqus In a separate PR, feel free to also add yourself to the list of contributors:
https://github.com/hodcroftlab/covariants/blob/master/.all-contributorsrc
by hand or with a CLI tool as described here
https://github.com/hodcroftlab/covariants/pull/48
and here
https://allcontributors.org/docs/en/emoji-key

**Comment by emmahodcroft** [comment]
@tonyqus Thank you again for this fantastic work! This is now live on the site, but I will wait to tweet until I hear back how I can acknowledge you best :)

Just as an additional point while checking - keeping the translations in sync is a challenge, and a couple of small things updated before this was merged:
- There's now a page for [23B](https://covariants.org/variants/23B.Omicron)
- Small addition of some text at the top of 22C (see 22C.Omicron.md file [here](https://github.com/hodcroftlab/covariants/commit/ceb723bccaa3f59112691562cb6b8a408bc74bd0#diff-f9c29bb96ae36f5f1af7431aa43185361a8684e994d5aa6566e043d1847e0ba6))
- Small addition of some text in 22C page ([here](https://github.com/hodcroftlab/covariants/commit/bed302bf3ea709d7fb0f321b12357c57329c668b))

No rush at all to add these! I just wanted to detail them since I caught them while merging this together! 😁 

Thank you again so much for your help with this!

**Comment by tonyqus** [comment]
Wow, thanks for the quick release. 

I'll submit a PR to fix some bugs and missing translation.

**Comment by emmahodcroft** [comment]
Just to let you know, I did a tweet thread today announcing the translations!

https://twitter.com/firefoxx66/status/1672234737455321088

**Pull request merged**
