### PR TITLE
Tweak mutations colors for better readability

### PR DESCRIPTION
**Pull request by ivan-aksamentov**
The aminoacid colors are taken from 
http://ugene.net/forum/YaBB.pl?num=1337064665

All colors are made dimmer and more pastel, to facilitate reading.
Might need a little more tweaking before it's perfect.

Resolves: #26

### CODE REVIEW

**Comment by emmahodcroft** [comment]
From a quick glance, I like this *a lot*. I will try to take a closer look, using a wider range of AAs to be sure we like how they look in 'real life'. My only comment thus far is that the `T` in Amino Acid may blend in a bit too much with the grey that's the color for the position:
image

However this may be highly monitor dependent...

**Review by ivan-aksamentov — COMMENTED** [review]
Made T a bit more saturated

**Comment by emmahodcroft** [comment]
Yes! I think that's great!

**Comment by emmahodcroft** [comment]
here's a demo with all AAs and all genes:
image

I think it's looking good!

**Comment by emmahodcroft** [comment]
I think perhaps the only one left I might edit is `B` - as it looks a lot like the `-` `X` `*` symbols.
I'll take a look.

**Comment by emmahodcroft** [comment]
Unless there are remaining thoughts about the colours or anything else, I'd be happy to merge this now!

**Comment by ivan-aksamentov** [comment]
LGTM. Definitive merge

**Pull request merged**
