### PR TITLE
New way to plot countries

### PR DESCRIPTION
**Pull request by emmahodcroft**
Adds new data from 4th Feb

But mostly it adds new countries to the plot and changes the order of countries plotting (most -> least sequences). Check this works ok!

### CODE REVIEW

**Comment by emmahodcroft** [comment]
Phew - it worked!

**Comment by emmahodcroft** [comment]
Very relieved - works perfectly! Of course, I never doubted Ivan's code for a minute. Only my own 😆

**Comment by emmahodcroft** [comment]
^ See above for why I can't be trusted. Managed to forget within the space of 2 minutes that I had already commented that it worked.... 🙃

**Comment by KarolineBragstad** [comment]
@emmahodcroft Why have you not included S477N in your SAR-CoV-2 variant builds?

**Comment by emmahodcroft** [comment]
Hi @KarolineBragstad ! The S477N lineage that seems like it likely emerged in France and then spread throughout Europe is indeed included, it's called 20A.EU2 (https://covariants.org/variants/20A.EU2). However, this does not include the earlier, independent lineage that was associated with an outbreak in Australia between Jun-Oct 2020.  I hope that helps!

**Pull request merged**
