### PR TITLE
Add 22A, B, C Clades

### PR DESCRIPTION
**Pull request by emmahodcroft**
Not ready to merge quite yet, but preparing.

Need to do a full run to include graph data for things to work properly...

### CODE REVIEW

**Comment by emmahodcroft** [comment]
Not entirely sure why failing. May be because I "turned on" display yet there is missing data (no run with the new definitions). This will be easier to debug on the full test branch.

**Comment by emmahodcroft** [comment]
I DID NOT MEAN TO CLOSE

**Comment by ivan-aksamentov** [comment]
@emmahodcroft Vercel says:

```
../content/clusters/22B.Omicron.md:22:16
Syntax error: Unterminated JSX contents.
  20 | <p><em parentName="p">{`Please help by providing links to further information about this variant if you can!`}</em></p>
  21 | <p><em parentName="p">{`(Thanks to Erik Boehm for his work on curating information relating to 22A-22C, which was used on these pages)`}</em></p>
> 22 |     </MDXLayout>
     |                 ^
  23 |   )
  24 | };
  25 | MDXContent.isMDXComponent = true
```

Something's wrong with the markdown content. Perhaps there's an unclosed tag? Or something that makes markdown parser to think there is. 

Also I cannot find a file `22A22B_Spike.md` which you import and use as `SpikeAB`. This might be it or it and something else.

**Comment by ivan-aksamentov** [comment]
It was missing an import

```tsx
import SpikeAB from 'content/clusters/22A22B_Spike.md'
```

in `content/clusters/22B.Omicron.md`

And a couple of `<br/>` tags were not closed.

**Comment by emmahodcroft** [comment]
Ah yes, I see how that happened... I was so careful to do it for 22A, then when I copied it all for 22B... 🙃

**Comment by emmahodcroft** [comment]
Thanks Ivan, I've also copied these over to my branch that'll have all the run on it!

**Comment by emmahodcroft** [comment]
Closing this because the trial PR worked so well, I'll just merge that in.

**Pull request closed without merging**
